# Generated by Django 5.1.1 on 2024-09-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=255, null=True)),
                ('urlSlug', models.CharField(max_length=50, null=True)),
                ('metaTitle', models.CharField(max_length=150, null=True)),
                ('metaDescription', models.TextField(null=True)),
                ('keywords', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
