# Generated by Django 5.1.1 on 2024-09-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='createdDate',
            field=models.DateField(null=True),
        ),
    ]
